### ISSUE TITLE
npm run dev gives an error

### ISSUE THREAD

**Issue by vzakharov-rxnt** [angular-tips/webpack-demo#12]
It's a terminating error - build stops, nothing happens.
```
c:\Git\webpack-demo\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
```

**Comment by Foxandxss** [comment]
Hello, I do appreciate you checking this repo, but it is 6 years old, probably nothing on it is current or valid.
